### LOGIN USER

POST http://localhost:8080/learning-management-system/v1/login
content-type: application/json

{
  "username": "ayubyoga",
  "password": "231231"
}

### LOGIN USER bad

POST http://localhost:8080/learning-management-system/v1/login

{
  "username": "ayubyoga",
  "password": "12345"
}
